#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/smerge
#
# IDENTIFICATION
#    src/backend/access/smerge/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/smerge
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = smerge.o
#smergefunc.o smergeinsert.o smergeovfl.o smergepage.o smergescan.o \
       smergesearch.o smergesort.o smergeutil.o smergevalidate.o

include $(top_srcdir)/src/backend/common.mk
