#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/smerge
#
# IDENTIFICATION
#    src/backend/access/smerge/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/smerge
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = smerge.o smbtree.o smmeta.o smsort.o

include $(top_srcdir)/src/backend/common.mk
